---
title: "mirl package"
output: html_notebook
---
#set up
```{r setup}
knitr::opts_knit$set(root.dir = "C:/Users/yingj/OneDrive/Documents/data-cleaned")
```

#clean data
```{r}
#load all substances
##0
opd <- read.csv("opioid.csv")
##1
amp <- read.csv("amphetamines.csv")
##2
ben <- read.csv("Benzodiazapines.csv")
##3
can <- read.csv("Cannabinoids.csv")
##4
coc <- read.csv("Cocaine metabolites.csv")
##5
mtd <- read.csv("Methadone.csv")
##6
mtp <- read.csv("Methamphetamine.csv")
##7
oxy <- read.csv("Oxycodone.csv")
##8
pph <- read.csv("Propoxyphene.csv")

#first four weeks for all 9 substances
first4wk <- data.frame(opd$BASELINE, opd$WK1, opd$WK2, opd$WK3, opd$WK4,
                       amp$BASELINE, amp$WK1, amp$WK2, amp$WK3, amp$WK4,
                       ben$BASELINE, ben$WK1, ben$WK2, ben$WK3, ben$WK4,
                       can$BASELINE, can$WK1, can$WK2, can$WK3, can$WK4,
                       coc$BASELINE, coc$WK1, coc$WK2, coc$WK3, coc$WK4,
                       mtd$BASELINE, mtd$WK1, mtd$WK2, mtd$WK3, mtd$WK4,
                       mtp$BASELINE, mtp$WK1, mtp$WK2, mtp$WK3, mtp$WK4,
                       oxy$BASELINE, oxy$WK1, oxy$WK2, oxy$WK3, oxy$WK4,
                       pph$BASELINE, pph$WK1, pph$WK2, pph$WK3, pph$WK4)

#treatement
t <- opd$treatment

#outcome
outcome <- opd[,c("WK21", "WK22", "WK23", "WK24")]

#2,-5 all treated as NA
#?These are people who showed up but result is unclear?
first4wk[first4wk==2] <- NA
first4wk[first4wk==-5] <- NA
apply(first4wk, 2, table)
```
#binary outcome
```{r}
outcome$pat <- apply(outcome, 1, paste, collapse = "")
y <- ifelse(outcome$pat=="0000", 0, 1)
table(y)
y <- as.factor(y)
```
#data
```{r}
p <- 1082
n <- nrow(first4wk)
f <- formula(y~.^2)

pdata <- cbind(first4wk, t, y)
pmat <- model.frame(f, pdata)
px.mat <- model.matrix(f, data = pdata)
py.mat <- pdata$y
```
#MIRL
```{r}
library(MIRL)
mirl(x=NULL,y,q2,im=5,E=NULL,lam=exp(seq(from=log(0.55),to=log(0.001),length.out=70)))
```